package com.gmail.solovev.webservice;

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.gmail.solovev package. An ObjectFactory allows you to programatically
 * construct new instances of the Java representation for XML content. The Java representation of XML
 * content can consist of schema derived interfaces and classes representing the binding of schema
 * type definitions, element declarations and model groups.  Factory methods for each of these are
 * provided in this class.
 */

@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.gmail.solovev
     */
    public ObjectFactory() { }

    /**
     * Create an instance of {@link GetFileNameResponse }
     */
    public GetFileNameResponse createGetFileNameResponse() {
        return new GetFileNameResponse();
    }

    /**
     * Create an instance of {@link Result }
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link GetFileNameRequest }
     */
    public GetFileNameRequest createGetFileNameRequest() {
        return new GetFileNameRequest();
    }
}
